version: "3.8"

services:
  open-ssh-server:
    build:
      context: .
    image: open-ssh-server
    container_name: open-ssh-server
    restart: unless-stopped
    environment:
      PUBLIC_KEY: "${PUBLIC_KEY}"
    ports:
      - "2223:22"